# Generated by Django 3.2 on 2023-06-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('feesamount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('feesamount', models.CharField(max_length=100)),
                ('paytype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('billdate', models.CharField(max_length=20)),
                ('reciptno', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('feesamount', models.CharField(max_length=100)),
                ('paytype', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
